# Generated by Django 4.2.7 on 2023-11-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0003_flight_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
