# Generated by Django 4.2.6 on 2023-12-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0004_alter_subscribers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
